
image: docker.io/library/centos:7

stages:
  - format

black:
  stage: format
  script:
  - yum install git -y
  - yum install python3-pip -y
  - export PYTHON_VERSION="py36"
  - FILES=$(git diff --name-only --diff-filter=ACMR $CI_COMMIT_SHA -- "*.py")
  - "[ -z '$FILES'] && exit 0"
  - pip install black
  - for file in $FILES; do black --check --fast --target-version $PYTHON_VERSION $file; done
