image: gitlab-registry.cern.ch/fts/fts-rest-flask:ci

stages:
  - static_code_analysis
  - tests
  - security
  - build

variables:
  MYSQL_DATABASE: ftsflask
  MYSQL_ROOT_PASSWORD: asdf
  PYTHONPATH: ./src:./src/fts3rest
  FTS3TESTCONFIG: ./src/fts3rest/fts3rest/tests/fts3testconfig_ci

black:
  # Check that every file has been formatted with black
  stage: static_code_analysis
  script:
  - black --check --fast --target-version py36 src/

pylint36:
  # Check that every file doesn't have syntax errors
  stage: static_code_analysis
  script:
  - python --version
  - pylint --output-format colorized --disable C,R,W src/ --ignored-modules=sqlalchemy

pylint37:
  stage: static_code_analysis
  script:
  - source ~/.bashrc
  - pyenv global $PY37
  - source $VENV_37/bin/activate
  - python --version
  - pylint --output-format colorized --disable C,R,W src/ --ignored-modules=sqlalchemy

pylint38:
  stage: static_code_analysis
  script:
  - source ~/.bashrc
  - pyenv global $PY38
  - source $VENV_38/bin/activate
  - python --version
  - pylint --output-format colorized --disable C,R,W src/ --ignored-modules=sqlalchemy

radon:
  # Check metrics for every file
  stage: static_code_analysis
  script:
  - source .gitlab-ci/radon.sh

functional_tests36:
  stage: tests
  services:
    - name: centos/mariadb:latest
      alias: mariadb
  script:
  - python --version
  - source .gitlab-ci/db.sh
  - coverage run --branch --source src/fts3rest/fts3rest/ --omit 'src/fts3rest/fts3rest/tests/*' -m pytest src/ -x
  - coverage report

functional_tests37:
  stage: tests
  services:
    - name: centos/mariadb:latest
      alias: mariadb
  script:
  - source ~/.bashrc
  - pyenv global $PY37
  - python --version
  - source $VENV_37/bin/activate
  - source .gitlab-ci/db.sh
  - coverage run --branch --source src/fts3rest/fts3rest/ --omit 'src/fts3rest/fts3rest/tests/*' -m pytest src/ -x
  - coverage report

functional_tests38:
  stage: tests
  services:
    - name: centos/mariadb:latest
      alias: mariadb
  script:
  - source ~/.bashrc
  - pyenv global $PY38
  - python --version
  - source $VENV_38/bin/activate
  - source .gitlab-ci/db.sh
  - coverage run --branch --source src/fts3rest/fts3rest/ --omit 'src/fts3rest/fts3rest/tests/*' -m pytest src/ -x
  - coverage report

bandit:
  # Find potential security issues in file. 
  # It's allowed to fail as it may detect false positives.
  allow_failure: true
  stage: security
  script:
  - bandit -r src/ --exclude src/fts3rest/fts3rest/tests/

wheel:
  stage: build
  script:
  - python3 setup.py bdist_wheel

sdist:
  stage: build
  script:
  - python3 setup.py sdist
