#
# FTS-REST-Server Docker file for the CI environment in Alma9Linux
#

FROM almalinux:9
LABEL maintainer="FTS Team, fts-support@cern.ch, CERN 2023"

# Add EPEL repos
RUN dnf install -y epel-release
RUN dnf clean metadata

# Build repo prerequisites
RUN dnf install -y createrepo

# Add FTS Dependencies repo (needed for Python3 packages)
RUN echo -e "[fts-depend]\nname=FTS3 Dependencies\nbaseurl=https://fts-repo.web.cern.ch/fts-repo/testing/fts-depend/el9/x86_64/\ngpgcheck=0\nenabled=1\npriority=2" > /etc/yum.repos.d/fts-depend.repo

# Add FTS repo from build artifacts stored in the alma9 directory
ADD alma9 /repo/fts
RUN createrepo /repo/fts
RUN echo -e "[fts-ci]\nname=FTS CI\nbaseurl=file:///repo/fts\ngpgcheck=0\nenabled=1\npriority=2" > /etc/yum.repos.d/fts.repo

# Add DMC repo
ARG dmcrepo=https://dmc-repo.web.cern.ch/dmc-repo/dmc-devel-el9.repo
ADD $dmcrepo /etc/yum.repos.d/dmc.repo
RUN dnf clean metadata

# Install FTS-REST-Server packages
RUN dnf install -y fts-rest-server fts-rest-server-selinux --enablerepo=crb

# Generate self signed host certificate
RUN /usr/libexec/httpd-ssl-gencerts

# Expose ports
EXPOSE 8446

# Entrypoint
CMD ["/usr/sbin/httpd", "-DFOREGROUND"]
